### ISSUE TITLE
nmap

### ISSUE THREAD

**Issue by danielmenezesbr** [Srendi/AWS-SCAN#1]
The package python-nmap needs nmap on host.

How your script can executed on lambda without nmap?

When I try to exec python-nmap, lambda show it:

```
START RequestId: fd4c1e1f-cb47-11e7-a453-c9cbb42ce8fd Version: $LATEST
'nmap program was not found in path. PATH is : /usr/local/bin:/usr/bin/:/bin': PortScannerError
Traceback (most recent call last):
  File "/var/task/handler.py", line 6, in hello2
    nm = nmap.PortScanner()
  File "/var/task/nmap/nmap.py", line 131, in __init__
    os.getenv('PATH')
PortScannerError: 'nmap program was not found in path. PATH is : /usr/local/bin:/usr/bin/:/bin'
```

**Comment by prem548** [comment]
@danielmenezesbr @Srendi By any chance did you guys figure out to overcome this problem. I am having same issue while writing a nmap Utility on AWS lambda.
